/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // mySidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  mySidebar: [
    {
      type: 'category',
      label: '📟 Extract subjects',
      link: {
        type: 'doc',
        id: 'extract/index',
      },
      items: ['extract/imaluum/index', 'extract/prereg/index'],
    },
    {
      type: 'category',
      label: '🧑🏼‍💻 For developers',
      link: {
        type: 'doc',
        id: 'extract/index',
      },
      items: ['devs/albiruni', 'devs/input-parser-api'],
    },
  ],

};

module.exports = sidebars;
